### ISSUE TITLE
UI: undo has too much granularity

### ISSUE THREAD

**Issue by lf-** [ubc-carnap-team/Rudolf#115] opened 2021-07-24 03:53 UTC
In working with the widget, I've found myself hitting the undo button a huge number of times relative to the number of perceived actions I've done. I'd like if it would just undo say, changes in the tree.

Currently I've had to hit it upwards of 6 times for undoing one split action because it tracks text changes as well as some kind of invisible state, I'm not sure what that state is.

**Comment by McTano** [comment] 2021-07-24 20:14
Duplicate of #90.

Tristan

**Closed** 2021-07-24 20:15 UTC
Labels: UI
